name = "go2do-server"
compatibility_date = "2024-02-08"
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "go2do-db"
database_id = "97f6097a-b42d-433c-b442-640561865bdd"

[[kv_namespaces]]
binding = "GO2DO_KV"
id = "7ea2b9bfc3b740209e33859c5140bea3"
preview_id = "preview_kv_id"

[vars]
ENVIRONMENT = "dev"
